data:
  data_dir: data
  split_ratio: 0.9
  raw_data_url: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
  raw_data_path: data/input.txt
  train_data_path: data/train_data.pt
  val_data_path: data/val_data.pt
  encoding_dict_path: data/encoding_dict.pkl
  decoding_dict_path: data/decoding_dict.pkl

train_baseline:
  vocab_size: 65
  batch_size: 32
  block_size: 8
  max_iters: 3000
  eval_interval: 300
  learning_rate: 1e-2
  eval_iters: 200

train_gpt:
  vocab_size: 65
  batch_size: 32 
  block_size: 256 
  max_iters: 5000
  eval_interval: 500
  learning_rate: 3e-4
  eval_iters: 200
  n_embd: 384
  n_head: 6
  n_layer: 6
  dropout: 0.2

models:
  models_dir: models
  baseline_path: models/baseline_model.pth
  gpt_path: models/gpt_model.pth

generate:
  outputs_dir: outputs
  max_new_tokens: 1000
  baseline_output: outputs/baseline_text.txt
  gpt_output: outputs/gpt_text.txt

hydra:
  run:
    dir: ./hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}